# Generated by Django 5.0.6 on 2024-07-03 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contexts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=128)),
                ('version', models.CharField(max_length=8)),
                ('vocab', models.CharField(max_length=64)),
                ('base', models.CharField(max_length=128)),
                ('filename', models.CharField(max_length=128)),
                ('subcontexts', models.CharField(blank=True, max_length=256, null=True)),
                ('updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'contexts',
                'managed': True,
            },
        ),
    ]
