# Generated by Django 5.0.6 on 2024-07-08 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contexts', '0002_contexts_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contexts',
            name='base',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='contexts',
            name='description',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='contexts',
            name='filename',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='contexts',
            name='version',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='contexts',
            name='vocab',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
