# Generated by Django 5.0.6 on 2024-07-11 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contexts', '0003_alter_contexts_base_alter_contexts_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contexts',
            name='language',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
