# Generated by Django 5.0.6 on 2024-07-03 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contexts', '0001_initial'),
        ('terms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContextsFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField()),
                ('context', models.ForeignKey(db_column='context_id', on_delete=django.db.models.deletion.DO_NOTHING, to='contexts.contexts')),
                ('term', models.ForeignKey(db_column='term_id', on_delete=django.db.models.deletion.DO_NOTHING, to='terms.terms')),
            ],
            options={
                'db_table': 'contexts_fields',
                'managed': True,
            },
        ),
    ]
