# Generated by Django 5.0.6 on 2024-07-07 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contexts', '0002_contexts_project'),
        ('contexts_fields', '0001_initial'),
        ('fields', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contextsfields',
            name='term',
        ),
        migrations.AddField(
            model_name='contextsfields',
            name='field',
            field=models.ForeignKey(blank=True, db_column='field_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='fields.fields'),
        ),
        migrations.AlterField(
            model_name='contextsfields',
            name='context',
            field=models.ForeignKey(blank=True, db_column='context_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contexts.contexts'),
        ),
    ]
