# Generated by Django 5.0.6 on 2024-07-04 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onts', '0002_onts_delete_nspaces'),
        ('terms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='terms',
            name='nspace',
        ),
        migrations.AddField(
            model_name='terms',
            name='ont',
            field=models.ForeignKey(db_column='ont_id', default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='onts.onts'),
        ),
    ]
