# Generated by Django 5.0.6 on 2024-07-08 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terms', '0002_remove_terms_nspace_terms_ont'),
    ]

    operations = [
        migrations.AddField(
            model_name='terms',
            name='iri',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
