# Generated by Django 5.0.6 on 2024-07-04 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('abbrev', models.CharField(blank=True, max_length=64, null=True)),
                ('description', models.CharField(max_length=128)),
                ('homepage', models.CharField(max_length=128)),
                ('apiurl', models.CharField(max_length=256)),
                ('headers', models.CharField(blank=True, max_length=256, null=True)),
                ('updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'servers',
                'managed': True,
            },
        ),
    ]
