# Generated by Django 5.0.6 on 2024-07-07 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0002_servers_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='servers',
            name='apikey',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
