# Generated by Django 5.0.6 on 2024-07-03 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nspaces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('ns', models.CharField(max_length=8)),
                ('path', models.CharField(max_length=64, unique=True)),
                ('homepage', models.CharField(max_length=128)),
                ('updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'onts',
                'managed': True,
            },
        ),
    ]
