# Generated by Django 5.0.6 on 2024-07-04 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onts', '0001_initial'),
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Onts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('ns', models.CharField(max_length=8)),
                ('path', models.CharField(max_length=64, unique=True)),
                ('homepage', models.CharField(max_length=128)),
                ('updated', models.DateTimeField()),
                ('server', models.ForeignKey(db_column='server_id', on_delete=django.db.models.deletion.DO_NOTHING, to='servers.servers')),
            ],
            options={
                'db_table': 'onts',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='Nspaces',
        ),
    ]
