# Generated by Django 5.0.6 on 2024-07-05 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onts', '0002_onts_delete_nspaces'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='onts',
            options={'managed': True, 'ordering': ('name',)},
        ),
        migrations.AddField(
            model_name='onts',
            name='description',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
