# Generated by Django 5.0.6 on 2024-07-08 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onts', '0003_alter_onts_options_onts_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='onts',
            name='trmcnt',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
